[[Qt5Declarative]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2865524824b44100c2bddfb495e365a55c7bd00d"
libc = "glibc"
os = "linux"

    [[Qt5Declarative.download]]
    sha256 = "3a8ac803199492f8dc7e23cea1679eefe4351ab61f8139e7a9534d6e8be081eb"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Qt5Declarative]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3de8a6afdc708d18f013c3d100141cd89477f92b"
libc = "glibc"
os = "linux"

    [[Qt5Declarative.download]]
    sha256 = "58f199f2096cf84014d454f896d250ef37a8986d7de4b47532e3af09ae42d5de"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Qt5Declarative]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f9bdbbb8f279d246458b768b569153f396aae74"
libc = "glibc"
os = "linux"

    [[Qt5Declarative.download]]
    sha256 = "ec01a80a78a0750af0964bb20f8c33e46773a6ca9e092d7a8c73381241324d2c"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Qt5Declarative]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57a4f54a91b576a2f6e049490f05a397349ba53f"
libc = "glibc"
os = "linux"

    [[Qt5Declarative.download]]
    sha256 = "e8947bec5454c15804a892c40dda4f37c4e60417b37f1f824d7baea802b3da02"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Qt5Declarative]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "445e0cddb4af09eef86916811a66d087cc24d7cc"
libc = "glibc"
os = "linux"

    [[Qt5Declarative.download]]
    sha256 = "eb50fa7d36933e570d843de825f1c3df06999287d2dc7f69bfc19e8496222db3"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.i686-linux-gnu-cxx03.tar.gz"
[[Qt5Declarative]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4f19ff341628670560de45441917549587977b8"
libc = "glibc"
os = "linux"

    [[Qt5Declarative.download]]
    sha256 = "d12239e24a99dabce55ef6af4e0a89559a3b308d810fece623ff99b547e32581"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.i686-linux-gnu-cxx11.tar.gz"
[[Qt5Declarative]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a440b875d83c632402d0f7b2098a4156550e3ed9"
libc = "glibc"
os = "linux"

    [[Qt5Declarative.download]]
    sha256 = "9d3c1a0f654173f026e8145d40ff7bab2d7ca3001dd36d1f3fd7b9905e1bf8d5"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Qt5Declarative]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba9f4836f75c18e8000aa508f6d1184dcd277422"
libc = "glibc"
os = "linux"

    [[Qt5Declarative.download]]
    sha256 = "2802672c38e0eeda1c89331efebf0772237057aabd229610630968a55f1c1dc7"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Qt5Declarative]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3e804fc034699d2ab547f4e6086be7ea7011d702"
libc = "glibc"
os = "linux"

    [[Qt5Declarative.download]]
    sha256 = "bc1c6bf10cbd877392ab320436c071280fe2d781001843048d5d56824de8bdae"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Qt5Declarative]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22316083794383a983da23332b549c0f669fdc80"
libc = "glibc"
os = "linux"

    [[Qt5Declarative.download]]
    sha256 = "09905f5ccb7291538bfc2ed0a8aab1bc7fa86ee52b2bc797c1e29ea3b9aa2645"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Qt5Declarative]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d4f78ade621c2e3d4b2d251ac91cafc9d2a7988"
os = "freebsd"

    [[Qt5Declarative.download]]
    sha256 = "6f228f6a5e6b741df2c1386fcd1e6424c9ede01f9c911ebf0e81d56cc2a80891"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.x86_64-unknown-freebsd-cxx03.tar.gz"
[[Qt5Declarative]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b5e0b43b05025f39a1b86969b157519634a2666"
os = "freebsd"

    [[Qt5Declarative.download]]
    sha256 = "444234ac18da26fe0103e38f84589916ebc375802591a9f881454d683f2f2149"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.x86_64-unknown-freebsd-cxx11.tar.gz"
[[Qt5Declarative]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "510f1bcba79e0f7923fa4664f0a07bcde349a243"
os = "windows"

    [[Qt5Declarative.download]]
    sha256 = "796fda003d10d5ad7d2fac4a60cb21951d348ed98492b55ca24f338ab1a0e22d"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.i686-w64-mingw32-cxx03.tar.gz"
[[Qt5Declarative]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a945bffd910b1ad2e59a2b2feb296fe997bc59c"
os = "windows"

    [[Qt5Declarative.download]]
    sha256 = "34918f09e26a72851415e3c4eaf90bc22d05b49b6923da56cbb22eb60dcc950b"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.i686-w64-mingw32-cxx11.tar.gz"
[[Qt5Declarative]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "323db5ed208751caa13f66f692e96af442bd66f3"
os = "windows"

    [[Qt5Declarative.download]]
    sha256 = "c81b964d1953dd1b8419c374ecbe92c4af4a1980a6c8755e99a20aeb021d212d"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Qt5Declarative]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a39e2ee37eaf7c08166e917e06829039e36f357c"
os = "windows"

    [[Qt5Declarative.download]]
    sha256 = "66058abe52cfd761143f80ff12c88b584f373347ef5f069fb5eba62068c9de6c"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.x86_64-w64-mingw32-cxx11.tar.gz"
[[Qt5Declarative]]
arch = "aarch64"
git-tree-sha1 = "e3826af83f9f5732bc42e5a5c532599d18c9f4fa"
os = "macos"

    [[Qt5Declarative.download]]
    sha256 = "30d50bacd6fe1e84fef4029784603bca12ebec7a24b11d7525983d5a86b04df1"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.aarch64-apple-darwin.tar.gz"
[[Qt5Declarative]]
arch = "x86_64"
git-tree-sha1 = "3b14973e68066cae866a3943120d2a9bf7f9c83b"
os = "macos"

    [[Qt5Declarative.download]]
    sha256 = "bc618ac451f36a49fadf1248f1659497b58da7bcb66f57acecc7ab6f813938a1"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Declarative_jll.jl/releases/download/Qt5Declarative-v5.15.3+0/Qt5Declarative.v5.15.3.x86_64-apple-darwin.tar.gz"
